### ISSUE TITLE
Autocomplete for @mdi/js destructive

### ISSUE THREAD

**Issue by mririgoyen** [lukas-tr/vscode-materialdesignicons-intellisense#3]
Using the latest of VSCode and your (awesome) extension, I found an issue that has been troubling me.

This should illustrate the issue:
![broked](https://user-images.githubusercontent.com/1015040/54468819-10c41400-4767-11e9-9339-2763bf9c2e16.gif)

Thank you!

**Comment by lukas-tr** [comment]
I fixed this by adding the following settings:
- `materialdesigniconsIntellisense.kebabCase.noTextDeletionLanguages`
- `materialdesigniconsIntellisense.camelCase.noTextDeletionLanguages`
- `materialdesigniconsIntellisense.homeAssistant.noTextDeletionLanguages`

Just add the languages where this occurs to one of these arrays.

The reason for adding these settings is that vscode automatically replaces the current word with the text to insert only for some languages (like JavaScript). Additionally, when the typed text contains characters like `:` or `-` in JavaScript, vscode just inserts the completion instead of replacing `mdi:` or `mdi-`.

**Comment by paritel99** [comment]
I can’t understand at all where to install it.

- materialdesigniconsIntellisense.kebabCase.noTextDeletionLanguages
- materialdesigniconsIntellisense.camelCase.noTextDeletionLanguages
- materialdesigniconsIntellisense.homeAssistant.noTextDeletionLanguages

**Comment by andyfensham** [comment]
I also don't know where to install it.

**Comment by lukas-tr** [comment]
Open settings via <kbd>F1</kbd> and enter `preferences: open settings json`. You can then add those 3 entries. 

![image](https://user-images.githubusercontent.com/36337818/81813395-b3248680-9527-11ea-8b88-eb363903c6c9.png)

If you don't know the language identifier, you can list all languages by pressing <kbd>F1</kbd> and entering `change language mode`. The identifier will be in parentheses. 

![image](https://user-images.githubusercontent.com/36337818/81814122-a48a9f00-9528-11ea-9f82-e4add424aae4.png)
