### ISSUE TITLE
VSCode reports "Extension issue"

### ISSUE THREAD

**Issue by pedrolamas** [lukas-tr/vscode-materialdesignicons-intellisense#7]
The following is directly from VSCode "show running extensions" and clicking in "report issue"
--

- Issue Type: `Bug`
- Extension Name: `materialdesignicons-intellisense`
- Extension Version: `1.5.2`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 1587,
		"activateCallTime": 12,
		"activateResolvedTime": 0,
		"activationEvent": "workspaceContains:node_modules/.bin/jest"
	},
	"runtimeErrors": [
		{
			"name": "SyntaxError",
			"message": "Unexpected token, expected ; (37:9)"
		},
		{
			"name": "SyntaxError",
			"message": "Unexpected token, expected ; (37:9)"
		}
	]
}
```

**Comment by lukas-tr** [comment]
What did you do when this error occurred?

Does this still occur when all other extensions are disabled?

**Comment by pedrolamas** [comment]
Nothing special, actually, I was just editing my own website... the whole code and extensions I use can be seen here: https://github.com/pedrolamas/pedrolamas.com

**Comment by lukas-tr** [comment]
I can't reproduce this. The activation event this extension uses is `*`, but the one listed in the issue is `workspaceContains:node_modules/.bin/jest`, which is strange. It's also the same as https://github.com/jest-community/vscode-jest/blob/master/package.json#L27. Could you disable `vscode-jest`, relaunch vscode and check if this error still shows up?

**Comment by pedrolamas** [comment]
I can't repro it any more, so I'm closing this now... if I find a way to repro it consistently, I'll re-open and update!
